### ISSUE TITLE
FYI: NFS on Mac OS Catalina Broken in Vagrant

### ISSUE THREAD

**Issue by mattmcdonald-uk** [laravel/homestead#1294]
This isn't a Homestead issue, but an issue with the current Vagrant release and Mac OS Catalina when using NFS exports.

Until Vagrant is updated to resolve this issue, it might be worth highlighting it for users who have upgraded to Catalina and are unable to launch Homestead.

[Workaround](https://github.com/hashicorp/vagrant/issues/10961#issuecomment-526132132) is to prefix exports in `Homestead.yaml` with `/System/Volumes/Data/Users`, removing `~` and make the same change in `/etc/exports`.

e.g. `~/taylor/Laravel` would become `/System/Volumes/Data/Users/taylor/Laravel`.

Second potential issue with upgrading to Catalina is bash is being phased out for zsh, and users may have replaced their shell with zsh (or have it as default if it's a new install).

If so, the `homestead` function added to `~/.bash_profile` would need to be added to `~/.zshrc` instead. Simply renaming `~/.bash_profile` should work.

**Comment by svpernova09** [comment]
Here's the corresponding Vagrant issue: https://github.com/hashicorp/vagrant/issues/10961

**Comment by aske-cph** [comment]
As far as i can see the issue "should have been" resolved in the new Vagrant 2.2.6 release.
But updating ([following musikovs bullets](https://github.com/hashicorp/vagrant/issues/10961#issuecomment-542229104)) and now when running homestead up i get: 

```
homestead-7: /home/vagrant/Code => /home/vagrant/Code
A bindfs command failed to run!

Command (runned via sudo):
/usr/bin/bindfs --force-user=vagrant --force-group=vagrant --perms=u=rwX:g=rD:o=rD /home/vagrant/Code /home/vagrant/Code

Standard output:


Error output:
Could not open source directory
```

**Comment by pdolinaj** [comment]
Upgraded to latest Vagrant 2.2.6 and also today 2nd update of MACOs Catalina and still doesn't work.
When I specify the folder mapping to  -> type: "nfs" - it throws the usual errors and when I ssh to vagrant box, the synced folders are empty. When I remove the NFS option, it works fine.
