### ISSUE TITLE
Vagrant up, can't find mysql, skipping DB creation, ERROR 1698 (28000): Access denied for user 'root'@'localhost'

### ISSUE THREAD

**Issue by chimmel** [laravel/homestead#1812]
I am attempting to recover a previous configuration on a new installation. 

## Versions
  - Vagrant: Run `vagrant -v` to show the version. = vagrant 2.3.2
  - Provider: Virtualbox, VMWare, Hyper-V, or Parallels and its version. = virtualbox 6.1.40_Debian r154048, mutated to libvirt 
  - Homestead: You should be on the most recent `release` branch. = yes 12.2.0

**A lot of issues can be resolved by simply updating vagrant, provider or homestead.**
>**Note:** Virtualbox users, please upgrade to `6.x`. You'll need to download a newer version of [Virtualbox](https://www.virtualbox.org/wiki/Downloads).

## Host operating system
This is the operating system that you run locally. = Debian 11

## Homestead.yaml
```yaml
---
ip: "192.168.56.56"
memory: 2048
cpus: 2
provider: libvirt #virtualbox
ssl: true

authorize: ~/Homestead/.ssh/hs_rsa.pub

keys:
    - ~/Homestead/.ssh/hs_rsa

folders:
    - map: ~/Homeserve/hs
      to: /home/vagrant/hs
      type: "nfs"

sites:
    - map: default.hs
      to: /home/vagrant/hs/default

databases:
    - homestead

backup: true

features:
    - mariadb: true

services: # also tried without this first
    - enabled:
          - "mysql"
```

## Vagrant destroy & up output
Provide a link to a [GitHub Gist](https://gist.github.com/) containing the complete output of `vagrant destroy && vagrant up`.
https://gist.github.com/chimmel/21bdf925aa3352b00a98dc716d2e011a

## Expected behavior
What should have happened? Please include as much detail as possible.

Absence of this error?

## Actual behavior
What actually happened? Please include as much detail as possible.

First I would get output ending in this when running `vagrant up`:
```
homestead: Running: script: Creating MySQL / MariaDB Database: homestead     
homestead: We didn't find MySQL ($mysql), skipping $DB creation     
homestead: ERROR 1698 (28000): Access denied for user 'root'@'localhost' The SSH command responded with a non-zero exit status. Vagrant assumes that this means the command failed. The output for this command should be in the log above. Please read the output to determine what went wrong.
```
When I tried destroying for the above gist that was skipped? It happened several times already. But I still got the error trying to log in via ssh. 
After failed `vagrant destroy` I set `backup: false`. 

The output of `vagrant up` was too long to gather the beginning once it ended. 

I destroyed the box again, changed the provider to virtualbox, and:
```
g@a0S:~/Homestead$ vagrant status
The provider 'virtualbox' that was requested to back the machine
'homestead' is reporting that it isn't usable on this system. The           
reason is shown below:                                                      

VirtualBox is complaining that the installation is incomplete. Please       
run `VBoxManage --version` to see the error message which should contain    
instructions on how to fix this error.                                      
g@a0S:~/Homestead$ VBoxManage --version
WARNING: The character device /dev/vboxdrv does not exist.
         Please install the virtualbox-dkms package and the appropriate
         headers, most likely linux-headers-amd64.

         You will not be able to start VMs until this problem is fixed.
6.1.40_Debianr154048
g@a0S:~/Homestead$ sudo apt install virtualbox-dkms linux-headers-amd64
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
linux-headers-amd64 is already the newest version (5.10.149-2).
virtualbox-dkms is already the newest version (6.1.40-dfsg-1~fto11+1).
virtualbox-dkms set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

## Steps to reproduce
1. Install vagrant, vagrant-hostmanager, vagrant-hostsupdater, vagrant-libvirt, vagrant-virtualbox, vagrant-mutate
2. Add laravel/homestead box, mutate to libvirt 
3. Followed instructions here https://laravel.com/docs/9.x/homestead to clone the repository
4. Edited Homestead.yaml
5. Vagrant up

## References
Are there any other [GitHub issues](https://github.com/laravel/homestead/issues?utf8=%E2%9C%93&q=is%3Aissue) (open or closed) that should be linked here?

https://github.com/laravel/homestead/issues/453 
... I tried adding the line here https://github.com/laravel/homestead/issues/453#issuecomment-278694703 to after.sh and provisioning and nothing changed.

**Comment by chimmel** [comment]
Also to connect to the database from host OS I'm using [dbeaver-ce](https://dbeaver.io/) which I used before but would these be the correct connection data?

Server host = 192.168.56.56 (specified in Homestead.yaml)
Port = 33060 
username = homestead
password = secret

**Comment by chimmel** [comment]
I don't see the Homestead fancy text banner when I ssh in either, is that no longer done? or is it supposed to show?

**Comment by svpernova09** [comment]
This issue should be fixed in https://github.com/laravel/homestead/releases/tag/v13.3.2 You can do a `git pull origin release` to update your repo to the latest release branch. `vagrant destroy` and `vagrant up` should get you back up and going.

**Comment by maynor96** [comment]
I executed the following commands: 
`git pull origin release
``vagrant destroy
``vagrant up
`
After executing those commands, the problem persists.

What do you recommend me to do?

Regards,

**Comment by kiddtang** [comment]
Once I turned on the `- mariadb: true`, I encounter this too.

**Comment by maynor96** [comment]
I had to downgrade to **v13.2.1** and the issue is gone.
