### ISSUE TITLE
Zray auto injected in page

### ISSUE THREAD

**Issue by M0ter** [laravel/homestead#808]
## Versions
  - Vagrant: 2.0.2
  - Provider: Virtualbox
  - Homestead: v7.1.0
  - Box version is v5.1.0

## Host operating system
Windows 10

## Steps to reproduce
1. Start homestead box
2. See zray bar
3. ???

**Comment by jacovdbergh** [comment]
Would also like to know more.

Installed a new Homestead instance today, suddenly I have a Z-Ray bar.

**Comment by svpernova09** [comment]
This is a known bug, thanks for the report. I'm working on a fix atm.

If you don't wish to use Z-Ray you can add the following lines to your `after.sh`:

```
rm -rf /usr/lib/php/20170718/zray.so
rm -rf /etc/php/7.2/fpm/conf.d/zray.ini
```
I'm trying to get a workable fix resolved now, but I'm in an airport on limited battery power so a better solution is in progress with no current ETA except for "later today"

**Comment by jacovdbergh** [comment]
Thanks for looking into it.

**Comment by svpernova09** [comment]
https://github.com/laravel/homestead/releases/tag/v7.1.1 should resolve this

**Comment by belisarh** [comment]
Hmmm... on v7.1.2 we still see Z-Ray injected... Also adding those lines to after.ssh and re-provisioning does not cut it.

**Comment by svpernova09** [comment]
@belisarh 

Please post the full output of `vagrant destroy && vagrant up` and describe the behavior your seeing. (preferably as a new Homestead issue)

**Comment by svpernova09** [comment]
@chilio 

> @svpernova09 on latest homestead I needed to ssh to the box to apply your workaround, cause adding to after.sh and provisioning vm and/or reloading did't change anything.

As https://github.com/laravel/homestead/issues/808#issuecomment-363824853 says we've released a fix to resolve this but you will need to upgrade to get the fix.

> Concluding further... homestead was meant strictly for Laravel right?

I don't think it was ever "strictly" for Laravel. While it should serve Laravel developers we have been able to expand the offering and become a very well suited general PHP development environment.

> There is a great working package laravel-debugbar form barryvdh, which is optional and anybody can use it if they need or want to...

Yep, I'm a fan.

> From z-ray documentation I have not seen any breakthrough advantages of z-ray over laravel-debugbar, but probably I could be missing something here.

They're two different products offering similar things. It's up to the developer to pick one. The decision to include Z-Ray was me approaching Zend to ask about including it. Several people inside Zend helped contribute to getting Z-Ray into Homestead.

The issues we had where Z-Ray was forced on everyone was limited and was fixed in a timely manner (IMHO). No one should still be having these issues. You should always run the newest / latest base box and Homestead versions.

> And final thoughtful thought, my homestead environment is slowing down with this release, which should be opposite when upgrading from php 5.6 to 7.2 for example.
Therefore I've started to think of applying other approach for my dev environment and moving away from homestead :-(

There are *so many* things that can contribute to slowdowns in Vagrant. We also did find and fix a nasty bug where Z-Ray ini was being added to PHP 7.2 CLI SAPI and causing tons of CLI issues.  Just because your application should see a performance boost upgrading versions of PHP doesn't mean your development environment will. 

Homestead is fairly large. We're pushing ~1.5GB for the base box which is quite large. Considering how many things we pack in, I feel like it's an acceptable trade off.

**Comment by chilio** [comment]
@svpernova09  in the first place thank you for your detailed answer.

In my case it could mean, that I'm mounting too many files/domains, although I would rather not be concerned about these limitations... 

So at least, it will be good to have some info about that, in the docs - what limits do we have?

My homestead box has 2 vCPUs and 4 GB of RAM, no hidden processing, do you think it is not enough?
The other thing is that I'm using laravel project with a lot of composer and npm dependencies.
For sure this will slow things down...

But on the other hand, I didn't change anything in my dev setup, and load times dropped significantly when z-ray was on....

That's why I wanted to disable it in the first place, and that's why I found this thread....

But again my question is, what are advantages of z-ray over laravel-debugbar.
If there are any please elaborate or post links....

**Comment by svpernova09** [comment]
@chilio 

> In my case it could mean, that I'm mounting too many files/domains, although I would rather not be concerned about these limitations...

Then you should not use Virtualbox, you should move to VMware.

> So at least, it will be good to have some info about that, in the docs - what limits do we have?

There is no definitive way of knowing what the limits are because some people seem to run into the issue constantly, while others never do. The known facts are it's a problem isolated to Virtualbox's default folder share types and can sometimes be resolved by using NFS, however NFS has it's own latency issues with file changes.

> My homestead box has 2 vCPUs and 4 GB of RAM, no hidden processing, do you think it is not enough?
> The other thing is that I'm using laravel project with a lot of composer and npm dependencies.
For sure this will slow things down...

Composer and NPM dependencies will not slow down your project's execution time in any substantial way. Running these binaries *inside* Homestead will certainly run much slower than if you run them on your host OS.

FWIW, I run Homestead most often with the default settings (2GB RAM & 1 CPU)

> But again my question is, what are advantages of z-ray over laravel-debugbar.
If there are any please elaborate or post links....

I don't have enough experience either to answer this. Most of my practical usage of both tools is limited to ensuring my query count per page load is as lean as it can be.
