### ISSUE TITLE
MySQL 8 installation fails with user authentication in PHP

### ISSUE THREAD

**Issue by jhoopes** [laravel/homestead#977]
I could make a PR for this, but, wanted to create an issue first to know if it's something that we want to function this way or not, or create multiple kinds of users, homestead being the mysql user with the new authentication method, and a secondary user with the mysql_native_password

## Versions
  - Vagrant: 2.2.0
  - Provider: Virtualbox
  - Homestead: 7.19.2

## Host operating system
OSX

## Homestead.yaml
```yaml
ip: "192.168.10.10"
memory: 4096
cpus: 4
provider: virtualbox
name: "nginx-homestead"
elasticsearch: 6
mysql8: true
```

## Expected behavior

When using mysql8 and then using a subsequent laravel app, the database connection fails on the homestead / secret user due to it using the new authentication method.  Because PHP (as of 7.2) . doesn't yet have support for this authentication method, it will fail.  Instead, we can use the "mysql_native_password" functionality in the create user syntax to allow PHP to authenticate correctly.

## Actual behavior
Authentication fails when trying to connect with the created homestead user

## Steps to reproduce
1.  add mysql8:true to yaml file
2. re-create vagrant machine
3. try to run a Laravel application which fails on the authentication 

## References

Forge's own implementation of the provisioning script when selecting for mysql 8 uses the

CREATE USER 'root'@'%' IDENTIFIED WITH mysql_native_password BY 'password';

syntax to handle authentication.

**Comment by svpernova09** [comment]
Upgrade to master branch of this repo and destroy and vagrant up again, that should resolve this issue.

**Comment by jhoopes** [comment]
Hey @svpernova09, thanks for letting me know.  it wasn't fixed, but with this commit:
https://github.com/laravel/homestead/commit/d7f09d962d9d2a68c94b2a4008026e27c1b1a88e
where the service was restarted before creating the users, it now works as it should.

Thanks!
